version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      github_actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      pip:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      docker:
        patterns:
          - "*"
